workflows:
  hello-world-workflow:
    name: My Hello world workflow
    environment:
      groups:
        - my_test_group
      vars:
        PUBLIC_ENV: This is a public environment variable
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - '$FLUTTER_ROOT/.pub-cache' #dart cache
        - '$FLUTTER_ROOT' #flutter sdk cache
        - '$HOME/.gradle/caches' # gradle cache
        - '$HOME/Library/Caches/CocoaPods' # cocoapods cache
    scripts:
      - name: Print Hello world to the console
        script: 'echo Hello world'
      - name: Print secure introduction
        script: 'echo Value from test group is $INTRODUCTION'
      - name: Print plain introduction
        script: 'echo Plain Value from test group is $VISIBLE_INTRO'
      - name: Print public environment variable to console
        script: 'echo PUBLIC_ENV: $PUBLIC_ENV'
      - name: Print FLUTTER_ROOT
        script: 'echo FLUTTER_ROOT: $FLUTTER_ROOT'
      - name: Print HOME
        script: 'echo HOME: $HOME'
      - name: Print CM_BUILD_DIR
        script: 'echo CM_BUILD_DIR: $CM_BUILD_DIR'
      - name: Print done
        script: 'echo workflow done'
