workflows:
  hello-world-workflow:
    name: My Hello world workflow
    instance_type: mac_mini_m1
    max_build_duration: 10
    environment:
      groups:
        - my_test_group
      vars:
        PUBLIC_ENV: This is a public environment variable
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - '$FLUTTER_ROOT/.pub-cache' #dart cache
        - '$FLUTTER_ROOT' #flutter sdk cache
        - '$HOME/.gradle/caches' # gradle cache
        - '$HOME/Library/Caches/CocoaPods' # cocoapods cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
      cancel_previous_builds: true
    scripts:
      - name: Build android app
        script: flutter build apk
      - name: Build ios app
        script: flutter build ios
        ignore_failure: true
    artifacts:
      - build/app/outputs/apk/**/*.apk
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - ugochukwugospeli111@gmail.com
