workflows:
  hello-world-workflow:
    name: My Hello world workflow
    environment:
      groups:
        - my_test_group
      vars:
        PUBLIC_ENV: This is a public environment variable
    scripts:
      - name: Print Hello world to the console
        script: "echo Hello world"
      - name: Print secure introduction
        script: "echo Value from test group is $INTRODUCTION"
      - name: Print plain introduction
        script: "echo Plain Value from test group is $VISIBLE_INTRO"
      - name: Print public environment variable to console
        script: "echo PUBLIC_ENV: $PUBLIC_ENV"


