workflows:
  hello-world-workflow:
    name: My Hello world workflow
    environment:
      groups:
        - my_test_group
    scripts:
      - name: Print Hello world to the console
        script: "echo Hello world"
      - name: Print secure introduction
        script: "echo Value from test group is $INTRODUCTION"
      - name: Print plain introduction
        script: "echo Plain Value from test group is $VISIBLE_INTRO"


